# Generated by Django 4.1.2 on 2022-11-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_rate_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
