# Generated by Django 4.1.1 on 2022-11-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.CharField(max_length=500)),
                ('ABV', models.FloatField(null=True)),
                ('price', models.FloatField()),
                ('introduction', models.CharField(max_length=500)),
            ],
        ),
    ]
