# Generated by Django 4.1.2 on 2022-11-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(default="oz|ml", max_length=50),
        ),
    ]
