# Generated by Django 4.1.2 on 2022-12-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='color',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_eng',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
