from django.db import migrations, models
# Generated by Django 4.1.2 on 2022-11-07 05:54


class Migration(migrations.Migration):

    dependencies = [

        ("tag", "0002_alter_cocktailtag_cocktail_alter_cocktailtag_tag"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cocktailtag",
            constraint=models.UniqueConstraint(
                fields=("cocktail", "tag"), name="unique_tags_on_same_cocktail"
            ),
        ),
    ]
