from enum import Enum

class ErrorCode(Enum):
    INVALID_REQUEST=0
    COCKTAIL_NAME_BLANK=1
    COCKTAIL_COLOR_BLANK=2
    COCKTAIL_INTRO_BLANK=3
    COCKTAIL_RECIPE_BLANK=4

    NOT_ALLOWED=3000

    DATA_NOT_FOUND=4000

    CONFLICT=9000
    COCKTAIL_NAME_ALREADY_EXIST=9001
    COCKTAIL_ENG_NAME_ALREADY_EXIST=9002

    SERVER_ERROR=10000