# Generated by Django 4.1.2 on 2022-11-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktail", "0002_auto_20221026_1224"),
    ]

    operations = [
        migrations.AddField(
            model_name="cocktail",
            name="rate",
            field=models.FloatField(default=0.0),
        ),
    ]
