# Generated by Django 4.1.1 on 2022-11-07 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0004_alter_cocktail_filter_type_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='filter_type_one',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('(_[a-z|A-Z|ㄱ-ㅎ|가-힣|0-9]+)*')]),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='filter_type_two',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('(_[a-z|A-Z|ㄱ-ㅎ|가-힣|0-9]+)*')]),
        ),
    ]
