# Generated by Django 4.1.2 on 2022-11-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0003_cocktail_rate'),
        ('cocktail', '0005_alter_cocktail_filter_type_one_and_more'),
    ]

    operations = [
    ]
