# Generated by Django 4.1.2 on 2022-12-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0006_merge_20221107_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='color',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='name_eng',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
