# Generated by Django 4.1.1 on 2022-11-02 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0002_auto_20221026_1224'),
        ('ingredient_prepare', '0002_alter_ingredientprepare_cocktail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientprepare',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_prepare', to='cocktail.cocktail'),
        ),
        migrations.AddConstraint(
            model_name='ingredientprepare',
            constraint=models.UniqueConstraint(fields=('cocktail', 'ingredient'), name='unique_cocktail_ingredient_combination'),
        ),
    ]
